name: Docker CI Pipeline
run-name: ${{ github.actor }} is running out Docker CI Pipeline 🚀
on: [push]
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
       - name: Clone the repo
         uses: actions/checkout@v6
         with:
           fetch-depth: 0

       - name: Secret Scanning
         uses: gitleaks/gitleaks-action@v2
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
         
       - name: Lint Dockerfile with Hadolint
         uses: hadolint/hadolint-action@v3.1.0
         with:
           dockerfile: Dockerfile
           ignore: DL4000
           
       - name: Docker Build
         run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/helloworld-python:v1 .

       - name: Run Trivy vulnerability scanner
         uses: aquasecurity/trivy-action@v0.36.0
         with:
          image-ref: '${{ vars.DOCKERHUB_USERNAME }}/helloworld-python:v1'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

       - name: Login to Docker Hub
         uses: docker/login-action@v4
         with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }} 

       - name: Docker Push
         run: docker push ${{ vars.DOCKERHUB_USERNAME }}/helloworld-python:v1 

       - name: Run the Container
         run: docker run --name helloworld-python -itd -p 8080:8080 ${{ vars.DOCKERHUB_USERNAME }}/helloworld-python:v1 

       - name: View the Container
         run: docker ps  
         
  k8s-implementation:
    needs: docker-build-push
    runs-on: ubuntu-latest
    
    steps:
       - name: Clone the code
         uses: actions/checkout@v6
         
       - name: start minikube
         uses: medyagh/setup-minikube@latest

       - name: Try the cluster!
         run: kubectl get pods -A 

       - name: Create Deployment and Service
         run: |
            kubectl apply -f manifests/deployment.yaml
            kubectl apply -f manifests/service.yaml
            kubectl wait --for=condition=ready pod -l app=hello-world-python         
 
       - name: View Deployment and Service
         run: |
            kubectl get deployments
            kubectl get service
            
       - name: Test service URLs
         run: |
           minikube service list
           minikube service my-service --url
           echo "------------------opening the service------------------"
           curl $(minikube service my-service --url)

           #testing the changes 
